      subroutine help(ver_tag)
      character*256 ver_tag
      write(6,*)"          **** PROGRAM INSTRUCTION ***"
      write(6,*)" "
      write(6,*)ver_tag
      write(6,*)" "
      write(6,*)"*LIMITATION : -This program is ONLY for 2D system."
      write(6,*)"            : -It tries to find the VBM for first KPT,"
      write(6,*)"            :  it may result in some problem when you"
      write(6,*)"            :  dealing with metallic states. "
      write(6,*)"            :  Be careful!"
      write(6,*)"*NOTE1 The x,y,z components of each G value are given"
      write(6,*)"       in terms of the ig values and the components "
      write(6,*)"       of the recip. lattice vectors according to:"
      write(6,*)"        ig1*b1_x + ig2*b2_x + ig3*b3_x,"
      write(6,*)"        ig1*b1_y + ig2*b2_y + ig3*b3_y, and"
      write(6,*)"        ig1*b1_z + ig2*b2_z + ig3*b3_z, respectively,"
      write(6,*)"       with"
      write(6,*)"        ig1=ig(1,iplane),"
      write(6,*)"        ig2=ig(2,iplane), and"
      write(6,*)"        ig3=ig(3,iplane),"
      write(6,*)"       where iplane=1,2,...,nplane(k,ispin) is an "
      write(6,*)"       index incrementing the plane waves for specific"
      write(6,*)"       k and spin values"
      write(6,*)" "
      write(6,*)"*NOTE2 The energy eigenvalues are complex, as provided"
      write(6,*)"       in the WAVECAR file, but the imaginary part is "
      write(6,*)"       zero (at least for cases investigated thus far)"
      write(6,*)" "
      write(6,*)"*Syntax:berry -f file -kx nx -ky ny -s 2 -ii ni -if nf"
      write(6,*)"*   (or)berry -f file -kx nx -ky ny -s 2 -is n "
      write(6,*)" "
      write(6,*)"             ### POSSIBLE OPTIONS ###"
      write(6,*)" -f filename      : File name to be read"
      write(6,*)"                  : Default: WAVECAR"
      write(6,*)" -kx(ky) kx(ky)   : k-point grid of your system"
      write(6,*)" -s 2 or 1        : for the noncollinear case, -s 2"
      write(6,*)"                  : for the collinear or NM,   -s 1"
      write(6,*)"                  :  Default : 2 if ISPIN 1"
      write(6,*)"                  :          : 1 if ISPIN 2"
      write(6,*)" -ii(if) ni(nf)   : Once specified, berry curvature "
      write(6,*)"                  : for multiband (from ni-th to nf-th"
      write(6,*)"                  : state) states will be evaluated,"
      write(6,*)"                  : unless '-cd' is not 1."
      write(6,*)"                  :  Default -cd 0 -> -ii  1  -if VBM "
      write(6,*)"                  :          -cd 1 -> -ii VBM -if CBM"
      write(6,*)" -is n            : if specified, berry curvature for"
      write(6,*)"                  : single band (n-th band) will be "
      write(6,*)"                  : evaluated." 
      write(6,*)" -o filename      : Print Berry curvature distribution"
      write(6,*)"                  : to the 'filename.dat'             "
      write(6,*)"                  :  Default : BERRYCURV.dat          "
      write(6,*)" -kp np           : Print Berry curvature distribution"
      write(6,*)"                  : with extended BZ with 'np x np'-BZ"
      write(6,*)"                  :  Default : 1              "
      write(6,*)" -skp 1(or 0)     : Specify whether special K-points "
      write(6,*)"                  : will be printed in the SKP.dat "
      write(6,*)"                  : You may specify the points by hand"
      write(6,*)"                  : into the source code, the routine,"
      write(6,*)"                  : 'write_special_kpoint'"
      write(6,*)"                  :  Default : 0"
      write(6,*)" -ne  ne          : Specify total number of electrons"
      write(6,*)"                  : Usual insulating cases, you don't"
      write(6,*)"                  : need to specify it, program will "
      write(6,*)"                  : find total number of electrons,"
      write(6,*)"                  : but for semimetallic system, it "
      write(6,*)"                  : may be more clear to put by hand"
      write(6,*)" -cd  1(or 0)     : Calculate spin- and k-resolved"
      write(6,*)"                  : degree of optical polarization,"
      write(6,*)"                  : degree of circular polarization,"
      write(6,*)"                  : between valence & conduction band"
      write(6,*)"                  : If set to '1', Berry cuvature will"
      write(6,*)"                  : not be evaluated"
      write(6,*)"                  : You may set -ii and -if together,"
      write(6,*)"                  : defining VBM & CBM, respectively"
      write(6,*)"                  :  Default : 0"
      write(6,*)"  or -cd 2        : If -cd is set to 2, total spectrum"
      write(6,*)"     -ien init_e  : with respect to the enery will be "
      write(6,*)"     -fen fina_e  : evaluated. In this case, "
      write(6,*)"     -nediv ndiv  : -ien and -fen tag should be set by"
      write(6,*)"     -sigma sigma : hand. Otherwise, default value, "
      write(6,*)"                  : -ien  0  -fen 10 -nediv 1000 will "
      write(6,*)"                  : be applied. The output contains"
      write(6,*)"                  : degree of circular polarization "
      write(6,*)"                  : with respect to photon energy "
      write(6,*)"                  : for each k-point. Here, -sigma tag"
      write(6,*)"                  : sets a gaussian broadning factor"
      write(6,*)"  or -cd 3        : If -cd is set to 3, total spectrum"
      write(6,*)"     -klist lfile : with respect to the energy will be"
      write(6,*)"     -sw sw_file    evaluated. Same functionality with"
      write(6,*)"                    -cd 2, but instead calculate in   "
      write(6,*)"                    order of kpoints list provided in "
      write(6,*)"                    lklist file with -klist option"
      write(6,*)"                    The spectral weight with unfolded"
      write(6,*)"                    band structure file (sw_file) "
      write(6,*)"                    also should be be provided with "
      write(6,*)"                    option -sw ."
      write(6,*)"                    Note: use sw_file generated by"
      write(6,*)"                          VaspBandUnfolding" 
      write(6,*)"     -atlist afile: 'afile' contains information for"
      write(6,*)"                  : atom_projected band structure file"
      write(6,*)"                  : name. Total number of atom to be "
      write(6,*)"                  : highlighted, and atom indices"
      write(6,*)"                  : It works with -cd 2 and 3 only." 
      write(6,*)"                  : EX)  in afile, it read as follows"
      write(6,*)"                    DOS_atom_projected.dat "
      write(6,*)"                    6   # total atom in system   "
      write(6,*)"                    3   # total atom to read     "
      write(6,*)"                    1 2 5   # atom indices to read"
      write(6,*)" *** Angle resolved CD calculations: *****************"
      write(6,*)" * -theta theta   : angle along z-axis describing"
      write(6,*)" *					 the direction of the injecting light"
      write(6,*)" *					  Default: 0"
      write(6,*)" * -phi   phi     : angle along x-axis describing"
      write(6,*)" *					 the direction of the injecting light"
      write(6,*)" *					  Default: 0"
      write(6,*)" *					 "
      write(6,*)" *					 Example:"
      write(6,*)" * 				  Light from z-axis(surface normal):"
      write(6,*)" * 				   (theta,phi) = (0.0,0.0)"
      write(6,*)" * 				  Light from x-axis "
      write(6,*)" * 				   (theta,phi) = (90.0,0.0)"
      write(6,*)" * 				  Light from y-axis "
      write(6,*)" * 				   (theta,phi) = (90.0,90.0)"
      write(6,*)" *****************************************************"
      write(6,*)" -kubo  1(or 0)   : Calculate spin- and k-resolved"
      write(6,*)"         (or 2)   : Berry curvature using Kubo formula"
      write(6,*)"                  : for nn-th band"
      write(6,*)"                  : If it is set by 2, line-mode is"
      write(6,*)"                  : assumed so that the result will"
      write(6,*)"                  : not be sorted over the BZ. "    
      write(6,*)"                  : Note: nn can be ranged by"
      write(6,*)"                  : -ii and -if tag "
      write(6,*)"                  :  ex) -kubo 1 -ii 19 -if 22 "
      write(6,*)"                  :  => from 19 to 22 th eigenstate"
      write(6,*)"                  :     will be calculated and the"
      write(6,*)"                  :     result will be printed out to"
      write(6,*)"                  :     BERRYCURF_KUBO.EIG-NN.DAT and"
      write(6,*)"                  :     total Berry curvature (19-22)"
      write(6,*)"                  :     is in BERRYCURF_KUBO.DAT"
      write(6,*)"                  :  Default : -kubo 0 (no calc.)"
      write(6,*)" -ixt np -fbz f   : **For the special purpose"
      write(6,*)"                  : Read file 'f' and extend data to"
      write(6,*)"                  : np x np periodic field. Note that"
      write(6,*)"                  : -ixt option should be used with "
      write(6,*)"                  :'-fbz filename_of_.dat_file' option"
      write(6,*)" -vel 1 -is n     : **For the special purpose"
      write(6,*)"                  : Calculate velocity expectation "
      write(6,*)"                  : vaule (v_x, v_y) of n-th state"
      write(6,*)" -z2  1           : Calculate Z2 invariant   "
      write(6,*)"                  : Using Fukui's method (JSPJ 76,"
      write(6,*)"                  : 053702 2007) which is lattice "
      write(6,*)"                  : version of Fu and Kane method"
      write(6,*)"                  : (PRB 74, 195312 2006) "
      write(6,*)" -hf  1           : Use half BZ, ISYM=1 or 2, "
      write(6,*)"                  : currently only works with -z2 1"
      write(6,*)" -wf nb -k nk     : **For the special purpose"
      write(6,*)"  -ng nx,ny,nz    : Calculate real-space wavefunction"
      write(6,*)"  -im 1           : output will be written in "
      write(6,*)"  -ishift rx,ry,rz: PARCHG-W-K$k-E$wf-(IM)-SPIN$ispin"
      write(6,*)"                  : nb and nk : index of band & kpoint"
      write(6,*)"                  : -ng option determins nx,ny,nz grid"
      write(6,*)"                  :  for the cube: default=nbmax"
      write(6,*)"                  : -im option: plot imaginary?"
      write(6,*)"                  : -ishift: shift origin with respect"
      write(6,*)"                  :  to the direct coord. rx,ry,rz"
      write(6,*)" "
      write(6,*)"* default: -f WAVECAR -kx 2 -ky 2 -s 2 -ii 1 -if VBM &
                -kp 1"
      write(6,*)"* here, VBM is valence band maximum"
      write(6,*)" "
      write(6,*)"*Compilation:  gfortran or ifort. "
      write(6,*)" Flag '-assume byterecl' is required for ifort."
      write(6,*)" for OSX,  -Wl,-stack_size,0x80000000 may be required"
      write(6,*)" ex-noMPI)ifort -fpp -assume byterecl -mkl & 
                -o vaspberry vaspberry.f"
      write(6,*)" ex-MPI)mpif90 -DMPI_USE -mkl -fpp -assume byterecl &
                 -o vaspberry vaspberry.f"
      write(6,*)" ex-noMPI-gfortran) gfortran -I/opt/local/include &
                 -L/opt/local/lib/lapack/ &
                -l lapack -o vaspberry vaspberry_gfortran _serial.f"
!     write(6,*)" ex-MPI) mpif90   -DMPI_USE -mkl -fpp -assume byterecl -o vaspberry vaspberry.f "
!     write(6,*)" ex-MPI) mpiifort -DMPI_USE -mkl -fpp -assume byterecl -o vaspberry vaspberry.f "
      stop
      end subroutine help
